import { CarSpec } from './types/simulation'

export const CAR_SPECS_DATA: Record<string, CarSpec> = {
  '2017': {
    year: '2017',
    manufacturer: 'Formula One Exhibition // 2017 Spec',
    model: 'MCL32 // Widebody High-Downforce Concept',
    season: '2017 FIA Formula One Season',
    powerUnit: '1.6L V6 Turbo Hybrid',
    horsepower: '950+ HP @ 15,000 RPM',
    weight: '728 kg',
    fuel: 'High-Octane E10 Racing Fuel',
    hybridSystem: 'MGU-K & MGU-H Dual ERS System',
    transmission: '8-Speed Seamless Shift Sequential',
    topSpeed: '350 km/h (217.5 mph)',
    downforce: 'Aggressive Widebody Aero Package',
    brakeSystem: 'Brembo Carbon-Carbon Brake Discs',
    tyres: 'Pirelli Wide Profile Racing Compounds',
    suspension: 'Front & Rear Carbon Composite Wishbones',
    description: 'The 2017 technical regulations introduced wider front and rear wings, wider tyres, and increased downforce, resulting in significantly faster cornering speeds.',
    technicalOverview: [
      'Increased Chassis and Wing Width Regulations',
      'Wider Pirelli Tyre Contact Patch',
      'High-Efficiency Floor Diffuser Channels',
      'Enhanced Hybrid Energy Recovery Capabilities'
    ]
  },
  '2018': {
    year: '2018',
    manufacturer: 'Formula One Exhibition // 2018 Spec',
    model: 'MCL33 // Halo Safety Era Pioneer',
    season: '2018 FIA Formula One Season',
    powerUnit: '1.6L V6 Turbocharged Hybrid',
    horsepower: '970+ HP @ 15,000 RPM',
    weight: '733 kg',
    fuel: 'High-Octane E10 Synthetic Blend',
    hybridSystem: 'MGU-K (120 kW) + MGU-H Energy Recovery',
    transmission: '8-Speed Longitudinal Sequential',
    topSpeed: '352 km/h (218.7 mph)',
    downforce: 'Refined Bargeboard & Sidepod Vane Aero',
    brakeSystem: 'Carbon Matrix Discs & 6-Piston Calipers',
    tyres: 'Pirelli P Zero High-Downforce Compounds',
    suspension: 'Pushrod Front & Pullrod Rear Suspension',
    description: '2018 marked the mandatory introduction of the titanium Halo cockpit protection system, revolutionizing driver safety while maintaining peak aerodynamic efficiency.',
    technicalOverview: [
      'Mandatory Titanium Halo Cockpit Protection',
      'Complex Bargeboard Aerodynamic Flow Conditioners',
      'Integrated Engine Cover Shark Fin Refinements',
      'Optimized Hybrid Power Delivery Mapping'
    ]
  },
  '2019': {
    year: '2019',
    manufacturer: 'Formula One Exhibition // 2019 Spec',
    model: 'MCL34 // Simplified Wing Aero Package',
    season: '2019 FIA Formula One Season',
    powerUnit: '1.6L V6 Turbocharged Hybrid',
    horsepower: '985+ HP @ 15,000 RPM',
    weight: '743 kg',
    fuel: 'Petronas/Shell High-Efficiency Racing Fuel',
    hybridSystem: 'Advanced ERS Array with High Recovery Rate',
    transmission: '8-Speed Seamless Shift Sequential',
    topSpeed: '354 km/h (220.0 mph)',
    downforce: 'Simplified Front & Rear Wing Aerodynamics',
    brakeSystem: 'Ventilated Carbon-Carbon Brake Assemblies',
    tyres: 'Pirelli P Zero Range (C1 to C5 Compounds)',
    suspension: 'Double Wishbone Carbon Composite Suspension',
    description: 'Introduced simplified front wings and endplates designed to promote outwashing and reduce dirty air wake, enabling closer wheel-to-wheel overtaking.',
    technicalOverview: [
      'Simplified 2000mm Wide Front Wing Geometry',
      'Higher & Wider Rear Wing with Larger DRS Opening',
      'Simplified Front Brake Duct Airflow Channels',
      'Increased Fuel Allowance to 110 kg per Race'
    ]
  },
  '2020': {
    year: '2020',
    manufacturer: 'Formula One Exhibition // 2020 Spec',
    model: 'MCL35 // Peak High-Rake Concept',
    season: '2020 FIA Formula One Season',
    powerUnit: '1.6L V6 Turbo Hybrid Power Unit',
    horsepower: '1,000+ HP @ 15,000 RPM',
    weight: '746 kg',
    fuel: 'High-Efficiency Performance Racing Fuel',
    hybridSystem: 'MGU-K & MGU-H Dual Energy Recovery System',
    transmission: '8-Speed Sequential Semi-Automatic',
    topSpeed: '356 km/h (221.2 mph)',
    downforce: 'Peak Downforce High-Rake Aerodynamic Floor',
    brakeSystem: 'Lightweight Carbon Discs with Active Ducting',
    tyres: 'Pirelli Low-Profile Performance Racing Tyres',
    suspension: 'Pushrod Front & Pullrod Rear Suspension',
    description: 'Represented the fastest Formula 1 cars in history up to that point, achieving unprecedented cornering speeds and peak aerodynamic downforce before regulation changes.',
    technicalOverview: [
      'Peak Aerodynamic Downforce Generation',
      'Extreme High-Rake Floor and Diffuser Architecture',
      'Complex S-Duct and Nosecone Flow Conditioners',
      '1,000+ Horsepower Hybrid Power Unit Milestone'
    ]
  },
  '2021': {
    year: '2021',
    manufacturer: 'Aston Martin Cognizant F1 Team',
    model: 'AMR21 // High-Downforce Concept',
    season: '2021 FIA Formula One Season',
    powerUnit: 'Mercedes-AMG F1 M12 E Performance 1.6L V6 Turbo Hybrid',
    horsepower: '1,000+ HP @ 15,000 RPM',
    weight: '752 kg (Minimum Dry Weight)',
    fuel: 'Petronas Primax E10 High-Octane Racing Fuel',
    hybridSystem: 'MGU-K (120 kW) + MGU-H Energy Recovery System',
    transmission: '8-Speed Longitudinal Sequential Semi-Automatic',
    topSpeed: '355 km/h (220.6 mph)',
    downforce: 'High Ground Effect & Low Rake Concept',
    brakeSystem: 'Brembo Carbon-Carbon Discs & 6-Piston Aluminum Calipers',
    tyres: 'Pirelli P Zero 13-Inch Low Profile Racing Compounds',
    suspension: 'Front Pushrod & Rear Pullrod Carbon Composite Wishbones',
    description: 'The AMR21 marked Aston Martin\'s return to Formula One grid after 61 years. Built on a low-rake aerodynamic philosophy, featuring an aggressive green livery with lime accents.',
    technicalOverview: [
      'Low Rake Aerodynamic Floor Package',
      'Mercedes-AMG 1.6L V6 Turbocharger Integration',
      'Complex Front Wing Baffle Arrays',
      'Tailored Rear Diffuser Strakes'
    ]
  },
  '2022': {
    year: '2022',
    manufacturer: 'Aston Martin Aramco Cognizant F1 Team',
    model: 'AMR22 // Ground Effect Revolution',
    season: '2022 FIA Formula One Season',
    powerUnit: 'Mercedes-AMG F1 M13 E Performance 1.6L V6 Turbo Hybrid',
    horsepower: '1,010+ HP @ 15,000 RPM',
    weight: '798 kg (New Technical Regulations Standard)',
    fuel: 'E10 Sustainable Fuel Blend (10% Ethanol)',
    hybridSystem: 'Dual ERS Motor Generator Units (MGU-K 120kW)',
    transmission: '8-Speed Seamless Shift Sequential Gearbox',
    topSpeed: '348 km/h (216.2 mph)',
    downforce: 'Full Venturi Tunnel Ground Effect Underbody',
    brakeSystem: 'Carbon-Carbon Venting Discs with Integrated Brake Ducts',
    tyres: 'Pirelli 18-Inch Low-Profile Racing Tyres with Wheel Covers',
    suspension: 'Pushrod Front & Pushrod Rear Kinematic Suspension',
    description: 'Designed under the landmark 2022 FIA technical revolution introducing Venturi tunnel ground effect aerodynamics and 18-inch wheels for closer wheel-to-wheel racing.',
    technicalOverview: [
      'Full Venturi Tunnel Underbody Aerodynamics',
      '18-Inch Low Profile Pirelli Racing Wheels',
      'Simplified Wing Profiles to Reduce Dirty Air',
      'E10 Sustainable Fuel Engine Calibration'
    ]
  },
  '2023': {
    year: '2023',
    manufacturer: 'Aston Martin Aramco F1 Team',
    model: 'AMR23 // Pod-Sculpted Podium Challenger',
    season: '2023 FIA Formula One Season',
    powerUnit: 'Mercedes-AMG F1 M14 E Performance 1.6L Turbo Hybrid',
    horsepower: '1,020+ HP @ 15,000 RPM',
    weight: '798 kg',
    fuel: 'Advanced E10 High-Efficiency Racing Fuel',
    hybridSystem: 'MGU-K Direct Drive + MGU-H Exhaust Heat Recovery',
    transmission: '8-Speed Sequential Semi-Automatic with Carbon Casing',
    topSpeed: '352 km/h (218.7 mph)',
    downforce: 'Ultra High-Efficiency Deep Sidepod Gully Concept',
    brakeSystem: 'Carbon-Carbon 6-Piston Calipers with Active Cooling Channels',
    tyres: 'Pirelli P Zero Slick & Cinturato Wet Compounds',
    suspension: 'Optimized Anti-Dive Pushrod Front & Anti-Squat Rear',
    description: 'The breakthrough AMR23 secured 8 podium finishes in the 2023 F1 World Championship. Renowned for its radical deep sidepod channels and supreme cornering downforce.',
    technicalOverview: [
      'Radical Deep Sidepod Waterslide Channels',
      'Aggressive Floor Edge Wing Vortices',
      'Superior Slow and Medium Corner Downforce',
      'High-Efficiency Drag Reduction DRS System'
    ]
  },
  '2024': {
    year: '2024',
    manufacturer: 'Aston Martin Aramco F1 Team',
    model: 'AMR24 // High-Velocity Aero Evolution',
    season: '2024 FIA Formula One Season',
    powerUnit: 'Mercedes-AMG F1 M15 E Performance 1.6L V6 Turbo Hybrid',
    horsepower: '1,030+ HP @ 15,000 RPM',
    weight: '798 kg',
    fuel: 'Advanced Synthetic Blend E10 Fuel',
    hybridSystem: 'High-Efficiency Kinetic & Thermal ERS Array',
    transmission: '8-Speed Seamless Shift Sequential with Quick-Shift Clutch',
    topSpeed: '356 km/h (221.2 mph)',
    downforce: 'Refined Low-Drag Undercut Bodywork Package',
    brakeSystem: 'Lightweight Carbon-Carbon Discs with 3D Printed Titanium Calipers',
    tyres: 'Pirelli 18-Inch High-Thermal-Stability Rubber',
    suspension: 'Pushrod Front & Pullrod Rear Carbon Fiber Wishbones',
    description: 'An evolutionary masterpiece optimizing airflow underneath the chassis and refining straight-line speed efficiency while maintaining high cornering stability.',
    technicalOverview: [
      'Sculpted Undercut Sidepod Intakes',
      'High-Speed Efficiency Wing Profiles',
      'Lightweight Composite Chassis Architecture',
      'Refined Thermal Management Ducting'
    ]
  },
  '2025': {
    year: '2025',
    manufacturer: 'Aston Martin Aramco F1 Team',
    model: 'AMR25 // Championship Specification Concept',
    season: '2025 FIA Formula One Season',
    powerUnit: 'Mercedes-AMG F1 Ultra-Hybrid 1.6L V6 Power Unit',
    horsepower: '1,040+ HP @ 15,000 RPM',
    weight: '798 kg',
    fuel: '100% Advanced E10 Sustainable Fuel',
    hybridSystem: 'Enhanced Energy Recovery Unit with Extended Boost Duration',
    transmission: '8-Speed Ultra-Lightweight Carbon Matrix Gearbox',
    topSpeed: '358 km/h (222.4 mph)',
    downforce: 'Dynamic Vortex Generation Floor Matrix',
    brakeSystem: 'Custom Carbon Matrix Discs with Active Thermal Ducting',
    tyres: 'Pirelli Next-Gen Low Degradation Racing Compounds',
    suspension: 'Fully Active Kinematic Geometry Wishbone Suspension',
    description: 'Representing the absolute pinnacle of current-generation F1 ground-effect regulations before the 2026 overhaul, featuring extreme aerodynamic sculpture.',
    technicalOverview: [
      'Maximum Expansion Floor Venturi Tunnels',
      'Ultra-Lean Rear Engine Cover Packaging',
      'Extended MGU-K Boost Battery Mapping',
      'Zero-Flex Carbon Fiber Structural Components'
    ]
  },
  '2026': {
    year: '2026',
    manufacturer: 'Aston Martin Aramco Honda F1 Team',
    model: 'AMR26 // Next-Generation Active Aero Concept',
    season: '2026 FIA Formula One Technical Regulation Preview',
    powerUnit: 'Honda RA626H 1.6L V6 Turbocharged 100% Sustainable Energy Unit',
    horsepower: '1,050+ HP (350kW Electric / 350kW ICE Balanced)',
    weight: '768 kg (30kg Lighter Next-Gen Chassis Target)',
    fuel: '100% Advanced Advanced Drop-In Sustainable Fuel',
    hybridSystem: '350 kW High-Power Electric MGU-K (Nearly 500 Electric HP)',
    transmission: '6-Speed Compact Lightweight Sequential Gearbox',
    topSpeed: '362 km/h (224.9 mph)',
    downforce: 'Active Aerodynamics (Front & Rear Wing Mode Shifting)',
    brakeSystem: 'Regenerative Braking-Focused Carbon Fiber Brake System',
    tyres: 'Pirelli Narrow-Profile 18-Inch Sustainable Compound Tyres',
    suspension: 'Ultra-Compact Pushrod Kinematic Geometry Suspension',
    description: 'Previewing the revolutionary 2026 FIA regulations featuring 100% sustainable fuels, 350kW electric power split, active wing aerodynamics, and lighter agile chassis.',
    technicalOverview: [
      '100% Sustainable Fuel Powered Honda RA626H Unit',
      'Active Front & Rear Wing Drag-Reduction Modes',
      'Equal 50/50 Electric & Internal Combustion Power Split',
      'Lighter Agile Chassis Dimensions for Close Racing'
    ]
  }
}

export const DEFAULT_CAR_SPEC: CarSpec = CAR_SPECS_DATA['2023']
